# Generated by Django 4.2.30 on 2026-08-18 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification', models.CharField(choices=[('clean', 'Clean'), ('malicious', 'Malicious')], max_length=10)),
                ('confidence', models.FloatField()),
                ('reasons', models.JSONField(default=list)),
                ('model_version', models.CharField(default='heuristic-v1.0', max_length=64)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_result', to='files.uploadedfile')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='scanning.scanresult')),
            ],
        ),
    ]
